Corrected the docs per the changes from the spanmetrics processor to spanmetrics connector
jaegertracing/documentation pull request #632
Opened 2023-04-30 17:04 UTC by jkowall

Updating the docs per changes in Otel. I can also add a link to @pavolloffay 's tutorial, might be a good set of examples for users in the doc. Just let me know.

2023-04-30 18:06 UTC, yurishkuro requested changes
It looks like all line endings are changed, while the text changes are minor. Please make sure to keep the original line endings.

2023-05-01 01:47 UTC, albertteoh reviewed
Thanks for putting this together, Jonah. I've added a comment about the timing of this change.

2023-05-01 01:47 UTC, albertteoh commented on content/docs/next-release/spm.md
There are some breaking changes introduced in the spanmetrics connector. As such, I suggest we address https://github.com/jaegertracing/jaeger/issues/4345 first before we merge this change into documentation.

2023-05-02 18:48 UTC, jkowall commented
> It looks like all line endings are changed, while the text changes are minor. Please make sure to keep the original line endings.

I am not sure what you mean by line endings? I am also not sure why the full file changed when I only edited a few things. Probably has to do with copying files around.

2023-05-02 19:29 UTC, yurishkuro commented
I mean Unix v windows new-line

2023-06-05 04:05 UTC, yurishkuro commented
@jkowall I ran `dos2unix` on the file and it fixed the line endings.

@albertteoh is this PR still needed, or does the one you made already covers this?

2023-06-05 04:19 UTC, albertteoh commented
> @albertteoh is this PR still needed, or does the one you made already covers this?

The PR I made should cover this PR.

2023-06-05 04:36 UTC, closed without merging